/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as HowRouteImport } from './routes/how'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBuildSendRouteImport } from './routes/api/build/send'
import { Route as ApiBuildTokenStatusRouteImport } from './routes/api/build/token-status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildSendRoute = ApiBuildSendRouteImport.update({
  id: '/api/build/send',
  path: '/api/build/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildTokenStatusRoute = ApiBuildTokenStatusRouteImport.update({
  id: '/api/build/token-status',
  path: '/api/build/token-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/contact': typeof ApiContactRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/send': typeof ApiBuildSendRoute
  '/api/build/token-status': typeof ApiBuildTokenStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/contact': typeof ApiContactRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/send': typeof ApiBuildSendRoute
  '/api/build/token-status': typeof ApiBuildTokenStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/contact': typeof ApiContactRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/send': typeof ApiBuildSendRoute
  '/api/build/token-status': typeof ApiBuildTokenStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/contact'
    | '/demo'
    | '/dpa'
    | '/how'
    | '/login'
    | '/office'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/contact'
    | '/api/auth/$'
    | '/api/build/send'
    | '/api/build/token-status'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/demo'
    | '/dpa'
    | '/how'
    | '/login'
    | '/office'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/contact'
    | '/api/auth/$'
    | '/api/build/send'
    | '/api/build/token-status'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/contact'
    | '/demo'
    | '/dpa'
    | '/how'
    | '/login'
    | '/office'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/contact'
    | '/api/auth/$'
    | '/api/build/send'
    | '/api/build/token-status'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DpaRoute: typeof DpaRoute
  HowRoute: typeof HowRoute
  LoginRoute: typeof LoginRoute
  OfficeRoute: typeof OfficeRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildSendRoute: typeof ApiBuildSendRoute
  ApiBuildTokenStatusRoute: typeof ApiBuildTokenStatusRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/send': {
      id: '/api/build/send'
      path: '/api/build/send'
      fullPath: '/api/build/send'
      preLoaderRoute: typeof ApiBuildSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/token-status': {
      id: '/api/build/token-status'
      path: '/api/build/token-status'
      fullPath: '/api/build/token-status'
      preLoaderRoute: typeof ApiBuildTokenStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DpaRoute: DpaRoute,
  HowRoute: HowRoute,
  LoginRoute: LoginRoute,
  OfficeRoute: OfficeRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ApiContactRoute: ApiContactRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildSendRoute: ApiBuildSendRoute,
  ApiBuildTokenStatusRoute: ApiBuildTokenStatusRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
